# Generated by Django 4.2.3 on 2023-10-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autoprint_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='MEDIA/')),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autoprint_API.cliente')),
            ],
        ),
    ]
