# Generated by Django 4.2.3 on 2023-10-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autoprint_API', '0002_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressao',
            name='documento',
        ),
        migrations.AddField(
            model_name='impressao',
            name='id_document',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Autoprint_API.documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='file',
            field=models.FileField(upload_to='DOCUMENTOS/'),
        ),
    ]
