# Generated by Django 4.2.3 on 2023-10-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autoprint_API', '0003_remove_impressao_documento_impressao_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='id_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autoprint_API.documento'),
        ),
    ]
