# Generated by Django 4.2.3 on 2023-10-07 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Autoprint_API', '0004_alter_impressao_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='data_criacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
