# Generated by Django 4.2.3 on 2023-10-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoprint_API', '0005_alter_impressao_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='pedido',
            field=models.IntegerField(default=-1),
        ),
    ]
