# Generated by Django 4.2.3 on 2023-10-07 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autoprint_API', '0007_remove_pedido_id_impressora_pedido_id_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Autoprint_API.agente'),
        ),
    ]
