# Generated by Django 4.2.3 on 2023-10-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autoprint_API', '0009_alter_pedido_data_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='descricao',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='agente',
            name='foto',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='agente',
            name='token',
            field=models.CharField(default='', max_length=512),
        ),
    ]
