# Generated by Django 4.2.3 on 2023-10-27 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autoprint_API', '0010_alter_agente_descricao_alter_agente_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='id_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Autoprint_API.documento'),
        ),
    ]
